fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

admin_admin:
    resource: "@AdminAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

bootstrap_theme:
    resource: "@BootstrapThemeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation