admin_admin_homepage:
    path:     /
    defaults: { _controller: AdminAdminBundle:Default:index }
    
    
admin_admin_users:
    path:     /users
    defaults: { _controller: AdminAdminBundle:Default:users }

admin_admin_Category:
    path:     /category
    defaults: { _controller: AdminAdminBundle:Default:Category }

admin_admin_Topic:
    path:     /topics
    defaults: { _controller: AdminAdminBundle:Default:Topic }
    
admin_admin_messsages:
    path:     /messages
    defaults: { _controller: AdminAdminBundle:Default:messages }

admin_admin_delete:
     path:    /{id}
     requirements: {id: \d+}
     defaults: { _controller: AdminAdminBundle:Default:delete }
     methods: [DELETE]
    
admin_admin_admin:
    resource: "@AdminAdminBundle/Controller/"
    type:     annotation