<?php

namespace Bootstrap\ThemeBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

     /**
     * @param $pattern
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function QBLikeName($pattern){
        
        $qb = $this->createQueryBuilder('category');
        $qb->where($qb->expr()->like('category.name',':pattern'))
            ->setParameter('pattern',$pattern."%");
        
        return $qb;
        
    }
    
}