<?php

namespace Bootstrap\ThemeBundle\Repository;

/**
 * topicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class topicsRepository extends \Doctrine\ORM\EntityRepository
{
}
